name: Build Rust DLL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Позволяет запускать сборку вручную из интерфейса GitHub

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      # Убрано ограничение по версии Visual Studio
        
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore NuGet packages
      run: nuget restore sus/bebrinity.sln

    - name: Build DLL
      run: |
        msbuild sus/bebrinity.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:PlatformToolset=v142 /p:WindowsTargetPlatformVersion=10.0 /p:TargetFrameworkVersion=v4.7.2 /p:CppStandard=c++17

    # Альтернативный метод сборки через командную строку (закомментирован)
    # - name: Build DLL using command line
    #   run: |
    #     cd sus
    #     cl /EHsc /std:c++17 /LD /O2 /I. /Fesus.dll main.cpp /link user32.lib kernel32.lib wininet.lib d3d11.lib

    - name: Verify build output
      run: |
        if (Test-Path "x64/${{ matrix.configuration }}/bebrinity.dll") {
          echo "DLL successfully built at x64/${{ matrix.configuration }}/bebrinity.dll"
        } elseif (Test-Path "${{ matrix.configuration }}/bebrinity.dll") {
          echo "DLL successfully built at ${{ matrix.configuration }}/bebrinity.dll"
          mkdir -p x64/${{ matrix.configuration }}
          cp ${{ matrix.configuration }}/bebrinity.dll x64/${{ matrix.configuration }}/
        } else {
          echo "DLL not found in expected locations"
          exit 1
        }

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-dll-${{ matrix.platform }}-${{ matrix.configuration }}
        path: x64/${{ matrix.configuration }}/bebrinity.dll
        if-no-files-found: error
